name: spam-detection
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - nltk
  - wordcloud
  - ipywidgets
  - pip:
      - jupyter